"""PySide6 UI for Deep-Live-Cam.

Public API kept stable for the rest of the codebase:
    init(start, destroy, lang) -> _Window
        Returned object has .mainloop() that core.py calls.
    update_status(text)
        Thread-safe; routed through Qt signal when called off-UI.
    check_and_ignore_nsfw(target, destroy=None) -> bool
"""

from __future__ import annotations

import os
import platform
import queue
import sys
import tempfile
import threading
import time
from typing import Callable, List, Optional, Tuple

import cv2
import numpy as np
import requests
from PIL import Image, ImageOps
from PySide6.QtCore import (
    QObject,
    QThread,
    QTimer,
    Qt,
    Signal,
)
from PySide6.QtGui import QIcon, QImage, QPixmap
from PySide6.QtWidgets import (
    QApplication,
    QButtonGroup,
    QComboBox,
    QDialog,
    QFileDialog,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QLabel,
    QMainWindow,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QSlider,
    QStackedWidget,
    QVBoxLayout,
    QWidget,
)

import modules.globals
import modules.metadata
from modules.capturer import get_video_frame, get_video_frame_total
from modules.face_analyser import (
    add_blank_map,
    detect_many_faces_fast,
    detect_one_face_fast,
    ensure_landmarks,
    get_one_face,
    get_source_face,
    get_unique_faces_from_target_image,
    get_unique_faces_from_target_video,
    has_valid_map,
    reset_face_analyser,
    simplify_maps,
)
from modules.gettext import LanguageManager
from modules.gpu_processing import gpu_cvt_color, gpu_flip, gpu_resize
from modules.processors.frame.core import get_frame_processors_modules
from modules.utilities import (
    has_image_extension,
    is_image,
    is_video,
)
from modules import imread_unicode
from modules import swap_models
from modules.runtime_state import set_live_thread
from modules.virtual_camera import VirtualCamOutput
from modules.ui_theme import (
    THEME_MODES,
    SwitchRow,
    apply_theme,
    bind_icon,
    eyebrow,
)
from modules.ui_theme import tokens as theme_tokens
from modules.video_capture import VideoCapturer

if platform.system() == "Windows":
    from pygrabber.dshow_graph import FilterGraph

import json


# ─── constants ────────────────────────────────────────────────────────────

ROOT_HEIGHT = 640
ROOT_WIDTH = 900
THUMB_SIZE = 236
APP_ICON_PNG = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "icon.png")
APP_ICON_ICO = os.path.join(os.path.dirname(APP_ICON_PNG), "icon.ico")

PREVIEW_MAX_HEIGHT = 700
PREVIEW_MAX_WIDTH = 1200
PREVIEW_DEFAULT_WIDTH = 640
PREVIEW_DEFAULT_HEIGHT = 360

POPUP_WIDTH = 750
POPUP_HEIGHT = 810
POPUP_SCROLL_WIDTH = 720
POPUP_SCROLL_HEIGHT = 700

POPUP_LIVE_WIDTH = 900
POPUP_LIVE_HEIGHT = 820
POPUP_LIVE_SCROLL_WIDTH = 870
POPUP_LIVE_SCROLL_HEIGHT = 700

MAPPER_PREVIEW_SIZE = 100
SOURCE_TARGET_PREVIEW_SIZE = 200


# ─── modern dark stylesheet ───────────────────────────────────────────────

QSS = ""  # stylesheet is generated by modules.ui_theme.build_qss()


# ─── module-level state ───────────────────────────────────────────────────

_APP: Optional[QApplication] = None
_MAIN: Optional["MainWindow"] = None
_PREVIEW: Optional["PreviewWindow"] = None
_WEBCAM_PREVIEW: Optional["WebcamPreviewWindow"] = None
# How long to wait quietly for a live-preview worker to notice the stop flag
# before saying so. Shutdown then keeps waiting: it has to finish.
WORKER_SHUTDOWN_GRACE_MS = 30000
_MAPPER: Optional["MapperDialog"] = None
_LIVE_MAPPER: Optional["LiveMapperDialog"] = None
_LANG: Optional[LanguageManager] = None
_BRIDGE: Optional["_UIBridge"] = None


def _(text: str) -> str:
    """Translate via LanguageManager; falls back to identity."""
    if _LANG is None:
        return text
    return _LANG._(text)


# Preserve original cwd state for file dialogs.
_RECENT_SOURCE_DIR: Optional[str] = None
_RECENT_TARGET_DIR: Optional[str] = None
_RECENT_OUTPUT_DIR: Optional[str] = None

# QFileDialog filter strings, built from the canonical extension sets in
# globals so every dialog stays in sync (no hand-copied lists to drift).
_IMAGE_FILE_FILTER = "Images (" + " ".join(
    f"*{ext}" for ext in modules.globals.IMAGE_EXTENSIONS
) + ")"
_MEDIA_FILE_FILTER = "Media (" + " ".join(
    f"*{ext}" for ext in (*modules.globals.IMAGE_EXTENSIONS, *modules.globals.VIDEO_EXTENSIONS)
) + ")"
_VIDEO_FILE_FILTER = "Videos (" + " ".join(
    f"*{ext}" for ext in modules.globals.VIDEO_EXTENSIONS
) + ")"


# ─── image utilities ─────────────────────────────────────────────────────


def fit_image_to_size(image, width: int, height: int):
    """BGR ndarray → BGR ndarray scaled to fit within (width, height)."""
    if width is None and height is None or width <= 0 or height <= 0:
        return image
    h, w = image.shape[:2]
    ratio_w = width / w
    ratio_h = height / h
    ratio = min(ratio_w, ratio_h)
    new_size = (max(1, int(w * ratio)), max(1, int(h * ratio)))
    return gpu_resize(image, dsize=new_size)


def _bgr_to_qpixmap(bgr: np.ndarray) -> QPixmap:
    """Zero-copy BGR ndarray → QPixmap."""
    h, w = bgr.shape[:2]
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    qimg = QImage(rgb.data, w, h, w * 3, QImage.Format.Format_RGB888).copy()
    return QPixmap.fromImage(qimg)


def _pil_to_qpixmap(image: Image.Image) -> QPixmap:
    """PIL.Image → QPixmap."""
    image = image.convert("RGBA")
    data = image.tobytes("raw", "RGBA")
    qimg = QImage(data, image.width, image.height, QImage.Format.Format_RGBA8888)
    return QPixmap.fromImage(qimg.copy())


def render_image_preview(image_path: str, size: Tuple[int, int]) -> QPixmap:
    image = Image.open(image_path)
    if size:
        image = ImageOps.fit(image, size, Image.LANCZOS)
    return _pil_to_qpixmap(image)


def render_video_preview(
    video_path: str, size: Tuple[int, int], frame_number: int = 0
) -> Optional[QPixmap]:
    capture = cv2.VideoCapture(video_path)
    try:
        if frame_number:
            capture.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
        has_frame, frame = capture.read()
        if not has_frame:
            return None
        image = Image.fromarray(gpu_cvt_color(frame, cv2.COLOR_BGR2RGB))
        if size:
            image = ImageOps.fit(image, size, Image.LANCZOS)
        return _pil_to_qpixmap(image)
    finally:
        capture.release()


# ─── persistence ─────────────────────────────────────────────────────────


def save_switch_states():
    state = {
        "keep_fps": modules.globals.keep_fps,
        "keep_audio": modules.globals.keep_audio,
        "keep_frames": modules.globals.keep_frames,
        "many_faces": modules.globals.many_faces,
        "map_faces": modules.globals.map_faces,
        "poisson_blend": modules.globals.poisson_blend,
        "color_correction": modules.globals.color_correction,
        "nsfw_filter": modules.globals.nsfw_filter,
        "live_mirror": modules.globals.live_mirror,
        "live_resizable": modules.globals.live_resizable,
        "fp_ui": modules.globals.fp_ui,
        "show_fps": modules.globals.show_fps,
        "virtual_camera": modules.globals.virtual_camera,
        "ui_theme": getattr(modules.globals, "ui_theme", "system"),
        "swap_model": getattr(modules.globals, "swap_model", swap_models.DEFAULT_SWAP_MODEL),
        "face_detail": getattr(modules.globals, "face_detail", 1),
        "mask_coverage": getattr(modules.globals, "mask_coverage", 0.65),
        "restore_mouth": getattr(modules.globals, "restore_mouth", 0.0),
        "restore_eyes": getattr(modules.globals, "restore_eyes", 0.0),
        "mask_feather": getattr(modules.globals, "mask_feather", 0.45),
        "color_match": getattr(modules.globals, "color_match", False),
        "skin_smoothing": getattr(modules.globals, "skin_smoothing", 0.0),
        "face_brightness": getattr(modules.globals, "face_brightness", 0.0),
        "face_warmth": getattr(modules.globals, "face_warmth", 0.0),
        "frame_smoothing": getattr(modules.globals, "frame_smoothing", 0.0),
        "mouth_mask": modules.globals.mouth_mask,
        "show_mouth_mask_box": modules.globals.show_mouth_mask_box,
        "mouth_mask_size": modules.globals.mouth_mask_size,
        "capture_resolution": list(modules.globals.capture_resolution),
        "det_size": modules.globals.det_size,
    }
    try:
        with open("switch_states.json", "w") as f:
            json.dump(state, f)
    except OSError:
        pass


def load_switch_states():
    try:
        with open("switch_states.json", "r") as f:
            state = json.load(f)
        modules.globals.keep_fps = state.get("keep_fps", True)
        modules.globals.keep_audio = state.get("keep_audio", True)
        modules.globals.keep_frames = state.get("keep_frames", False)
        modules.globals.many_faces = state.get("many_faces", False)
        modules.globals.map_faces = state.get("map_faces", False)
        modules.globals.poisson_blend = state.get("poisson_blend", False)
        modules.globals.color_correction = state.get("color_correction", False)
        modules.globals.nsfw_filter = state.get("nsfw_filter", False)
        modules.globals.live_mirror = state.get("live_mirror", False)
        modules.globals.live_resizable = state.get("live_resizable", False)
        modules.globals.fp_ui = state.get("fp_ui", {"face_enhancer": False})
        modules.globals.show_fps = state.get("show_fps", False)
        modules.globals.virtual_camera = state.get("virtual_camera", False)
        modules.globals.ui_theme = state.get("ui_theme", "system")
        model = state.get("swap_model", swap_models.DEFAULT_SWAP_MODEL)
        modules.globals.swap_model = model if model in swap_models.SWAP_MODELS else swap_models.DEFAULT_SWAP_MODEL
        detail = state.get("face_detail", 1)
        modules.globals.face_detail = detail if detail in (1, 2, 4) else 1
        modules.globals.color_match = bool(state.get("color_match", False))
        for key, default in (("mask_coverage", 0.65), ("mask_feather", 0.45),
                             ("restore_mouth", 0.0), ("restore_eyes", 0.0)):
            try:
                setattr(modules.globals, key, min(1.0, max(0.0, float(state.get(key, default)))))
            except (TypeError, ValueError):
                setattr(modules.globals, key, default)
        for key, lo, hi in (("skin_smoothing", 0.0, 1.0), ("face_brightness", -1.0, 1.0),
                            ("face_warmth", -1.0, 1.0), ("frame_smoothing", 0.0, 0.8)):
            try:
                setattr(modules.globals, key, min(hi, max(lo, float(state.get(key, 0.0)))))
            except (TypeError, ValueError):
                setattr(modules.globals, key, 0.0)
        modules.globals.enable_interpolation = modules.globals.frame_smoothing > 0
        modules.globals.interpolation_weight = 1.0 - modules.globals.frame_smoothing
        # Mouth mask always starts disabled (slider at 0) on launch,
        # regardless of the persisted value — enable it explicitly each session.
        modules.globals.mouth_mask_size = 0.0
        modules.globals.mouth_mask = False
        modules.globals.show_mouth_mask_box = False
        # Validate persisted camera settings before trusting them — a hand-
        # edited/corrupt file shouldn't push a bad size into cv2/insightface.
        res = state.get("capture_resolution")
        if isinstance(res, (list, tuple)) and len(res) == 2:
            try:
                w, h = int(res[0]), int(res[1])
                if w > 0 and h > 0:
                    modules.globals.capture_resolution = (w, h)
            except (TypeError, ValueError):
                pass
        if state.get("det_size") in (160, 320, 640, 960, 1280):
            modules.globals.det_size = int(state["det_size"])
    except FileNotFoundError:
        pass
    except (OSError, json.JSONDecodeError):
        pass


# ─── thread-safe status bridge ───────────────────────────────────────────


class _UIBridge(QObject):
    """Single QObject that owns cross-thread signals."""

    statusChanged = Signal(str)


def _emit_status(text: str) -> None:
    if _BRIDGE is None:
        print(text)
        return
    _BRIDGE.statusChanged.emit(text)


# ─── public API ──────────────────────────────────────────────────────────


def update_status(text: str) -> None:
    """Thread-safe status update — uses signal if called off-UI thread."""
    _emit_status(_(text))
    if _APP is not None and QThread.currentThread() is _APP.thread():
        # On UI thread — flush events so the user sees the update during
        # long synchronous start() runs.
        _APP.processEvents()


def check_and_ignore_nsfw(target, destroy: Optional[Callable] = None) -> bool:
    from numpy import ndarray
    from modules.predicter import predict_frame, predict_image, predict_video

    check_nsfw = None
    if isinstance(target, str):
        check_nsfw = predict_image if has_image_extension(target) else predict_video
    elif isinstance(target, ndarray):
        check_nsfw = predict_frame

    if check_nsfw and check_nsfw(target):
        if destroy:
            destroy(to_quit=False)
        update_status("Processing ignored!")
        return True
    return False


# ─── camera enumeration (unchanged from tk version) ──────────────────────


def get_available_cameras() -> Tuple[List[int], List[str]]:
    if platform.system() == "Windows":
        try:
            graph = FilterGraph()
            devices = graph.get_input_devices()
            # Skip OBS Virtual Camera: it's our output device, reading it
            # back would loop the swapped feed into itself.
            pairs = [(i, d) for i, d in enumerate(devices)
                     if d != "OBS Virtual Camera"]
            if pairs:
                return [i for i, _d in pairs], [d for _i, d in pairs]
            return [], ["No cameras found"]
        except Exception as exc:
            print(f"Error detecting cameras: {exc}")
            return [], ["No cameras found"]

    if platform.system() == "Darwin":
        return [0, 1], ["Camera 0", "Camera 1"]

    # Linux probe
    indices: List[int] = []
    names: List[str] = []
    for i in range(10):
        cap = cv2.VideoCapture(f"/dev/video{i}")
        if cap.isOpened():
            indices.append(i)
            names.append(f"Camera {i}")
            cap.release()
    return (indices, names) if names else ([], ["No cameras found"])


# ─── main window ─────────────────────────────────────────────────────────


def _make_image_drop(text: str, size: Tuple[int, int]) -> QLabel:
    label = QLabel(text)
    label.setObjectName("imageDrop")
    label.setAlignment(Qt.AlignmentFlag.AlignCenter)
    label.setFixedSize(size[0], size[1])
    label.setText(text)
    return label


_Switch = SwitchRow


def _signed(v: int) -> str:
    return f"{v:+d}" if v else "0"


def _card(title: str = "", description: str = "") -> Tuple[QFrame, QVBoxLayout]:
    frame = QFrame()
    frame.setObjectName("card")
    layout = QVBoxLayout(frame)
    layout.setContentsMargins(20, 18, 20, 20)
    layout.setSpacing(12)
    if title:
        head = QVBoxLayout()
        head.setSpacing(2)
        heading = QLabel(title)
        heading.setObjectName("cardTitle")
        head.addWidget(heading)
        if description:
            desc = QLabel(description)
            desc.setObjectName("cardDesc")
            desc.setWordWrap(True)
            head.addWidget(desc)
        layout.addLayout(head)
    return frame, layout


def _hint(text: str) -> QLabel:
    label = QLabel(text)
    label.setObjectName("hint")
    label.setWordWrap(True)
    return label


def _rule() -> QFrame:
    line = QFrame()
    line.setObjectName("rule")
    return line


def _field(label: str, widget: QWidget) -> QVBoxLayout:
    col = QVBoxLayout()
    col.setSpacing(6)
    lab = QLabel(label)
    lab.setObjectName("fieldLabel")
    col.addWidget(lab)
    col.addWidget(widget)
    return col


def _button(text: str, variant: str = "", icon_name: str = "", icon_role: str = "fg",
            size: str = "") -> QPushButton:
    btn = QPushButton(text)
    if variant:
        btn.setProperty("variant", variant)
    if size:
        btn.setProperty("size", size)
    if icon_name:
        bind_icon(btn, icon_name, icon_role)
    btn.setCursor(Qt.CursorShape.PointingHandCursor)
    return btn


class MainWindow(QMainWindow):
    PAGE_LIVE, PAGE_FILE, PAGE_QUALITY = 0, 1, 2

    def __init__(self, start_cb: Callable, destroy_cb: Callable):
        super().__init__()
        load_switch_states()
        self._start_cb = start_cb
        self._destroy_cb = destroy_cb

        self.setWindowTitle(f"{modules.metadata.name} {modules.metadata.version}")
        self.setMinimumSize(ROOT_WIDTH, ROOT_HEIGHT)
        self.resize(1080, 760)

        root = QWidget()
        row = QHBoxLayout(root)
        row.setContentsMargins(0, 0, 0, 0)
        row.setSpacing(0)
        row.addWidget(self._build_sidebar())

        content = QWidget()
        content.setObjectName("content")
        col = QVBoxLayout(content)
        col.setContentsMargins(0, 0, 0, 0)
        col.setSpacing(0)

        self._face_card = self._build_face_card()
        self._face_slots = {}
        self._stack = QStackedWidget()
        self._stack.addWidget(self._scroll(self._build_live_page()))
        self._stack.addWidget(self._scroll(self._build_file_page()))
        self._stack.addWidget(self._scroll(self._build_quality_page()))
        col.addWidget(self._stack, 1)
        col.addWidget(self._build_status_bar())
        row.addWidget(content, 1)
        self.setCentralWidget(root)

        self._nav_buttons[self.PAGE_LIVE].setChecked(True)
        self._show_page(self.PAGE_LIVE)

    # ── shell ────────────────────────────────────────────────────────────

    def _build_sidebar(self) -> QFrame:
        bar = QFrame()
        bar.setObjectName("sidebar")
        bar.setFixedWidth(232)
        col = QVBoxLayout(bar)
        col.setContentsMargins(12, 16, 12, 12)
        col.setSpacing(2)

        brand = QHBoxLayout()
        brand.setContentsMargins(8, 0, 0, 0)
        brand.setSpacing(10)
        chip = QLabel()
        chip.setFixedSize(30, 30)
        logo = QPixmap(APP_ICON_PNG)
        if not logo.isNull():
            logo.setDevicePixelRatio(2)
            chip.setPixmap(logo.scaled(60, 60, Qt.AspectRatioMode.KeepAspectRatio,
                                       Qt.TransformationMode.SmoothTransformation))
        brand.addWidget(chip)
        names = QVBoxLayout()
        names.setSpacing(0)
        title = QLabel(modules.metadata.name)
        title.setObjectName("brand")
        version = QLabel(f"v{modules.metadata.version} · {_('Open source')}")
        version.setObjectName("brandVersion")
        names.addWidget(title)
        names.addWidget(version)
        brand.addLayout(names, 1)
        col.addLayout(brand)
        col.addSpacing(22)

        nav_label = eyebrow(_("Workspace"))
        nav_label.setContentsMargins(12, 0, 0, 4)
        col.addWidget(nav_label)

        self._nav_group = QButtonGroup(self)
        self._nav_group.setExclusive(True)
        self._nav_buttons = []
        for idx, (text, icon_name) in enumerate([
            (_("Live webcam"), "video"),
            (_("Photo && Video"), "image"),
            (_("Face quality"), "sliders-horizontal"),
        ]):
            btn = QPushButton(text)
            btn.setObjectName("navItem")
            btn.setCheckable(True)
            btn.setCursor(Qt.CursorShape.PointingHandCursor)
            bind_icon(btn, icon_name, "muted_fg")
            btn.clicked.connect(lambda _c=False, i=idx: self._show_page(i))
            self._nav_group.addButton(btn, idx)
            self._nav_buttons.append(btn)
            col.addWidget(btn)

        col.addStretch(1)
        rule = QFrame()
        rule.setObjectName("sidebarRule")
        col.addWidget(rule)
        col.addSpacing(6)

        self.btn_theme = QPushButton()
        self.btn_theme.setObjectName("navItem")
        self.btn_theme.setCursor(Qt.CursorShape.PointingHandCursor)
        self.btn_theme.setToolTip(_("Switch between system, light and dark theme"))
        self.btn_theme.clicked.connect(self._on_cycle_theme)
        col.addWidget(self.btn_theme)
        self._refresh_theme_button()

        self.btn_destroy = QPushButton(_("Quit"))
        self.btn_destroy.setObjectName("navItem")
        self.btn_destroy.setCursor(Qt.CursorShape.PointingHandCursor)
        bind_icon(self.btn_destroy, "power", "destructive")
        self.btn_destroy.setToolTip(_("Stop everything and close the application"))
        self.btn_destroy.clicked.connect(lambda: self._destroy_cb())
        col.addWidget(self.btn_destroy)
        return bar

    def _build_status_bar(self) -> QFrame:
        bar = QFrame()
        bar.setObjectName("statusBar")
        bar.setFixedHeight(38)
        row = QHBoxLayout(bar)
        row.setContentsMargins(32, 0, 24, 0)
        row.setSpacing(10)
        self._status_label = QLabel(_("Ready"))
        self._status_label.setObjectName("statusLabel")
        row.addWidget(self._status_label, 1)
        provider = "GPU · CUDA" if any("CUDA" in p for p in modules.globals.execution_providers) else (
            "GPU · DirectML" if any("Dml" in p for p in modules.globals.execution_providers) else "CPU")
        pill = QLabel(provider)
        pill.setObjectName("pill")
        row.addWidget(pill)
        return bar

    @staticmethod
    def _scroll(page: QWidget) -> QScrollArea:
        area = QScrollArea()
        area.setWidgetResizable(True)
        area.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        area.setWidget(page)
        return area

    @staticmethod
    def _page(kicker: str, title: str, description: str) -> Tuple[QWidget, QVBoxLayout]:
        page = QWidget()
        page.setObjectName("page")
        outer = QHBoxLayout(page)
        outer.setContentsMargins(32, 30, 32, 32)
        body_widget = QWidget()
        body_widget.setObjectName("page")
        body_widget.setMaximumWidth(920)
        body = QVBoxLayout(body_widget)
        body.setContentsMargins(0, 0, 0, 0)
        body.setSpacing(16)
        head = QVBoxLayout()
        head.setSpacing(4)
        head.addWidget(eyebrow(kicker))
        t = QLabel(title)
        t.setObjectName("pageTitle")
        head.addWidget(t)
        d = QLabel(description)
        d.setObjectName("pageDesc")
        d.setWordWrap(True)
        head.addWidget(d)
        body.addLayout(head)
        body.addSpacing(6)
        outer.addWidget(body_widget, 1)
        outer.addStretch(0)
        return page, body

    def _show_page(self, index: int) -> None:
        self._stack.setCurrentIndex(index)
        if index < len(self._nav_buttons):
            self._nav_buttons[index].setChecked(True)
        for i, btn in enumerate(self._nav_buttons):
            bind_icon(btn, ["video", "image", "sliders-horizontal"][i],
                      "primary" if i == index else "muted_fg")
        slot = self._face_slots.get(index)
        if slot is not None:
            slot.insertWidget(0, self._face_card)

    # ── theme ────────────────────────────────────────────────────────────

    def _refresh_theme_button(self) -> None:
        mode = getattr(modules.globals, "ui_theme", "system")
        label = {"system": _("Theme: System"), "light": _("Theme: Light"), "dark": _("Theme: Dark")}[mode]
        self.btn_theme.setText(label)
        bind_icon(self.btn_theme, {"system": "monitor", "light": "sun", "dark": "moon"}[mode], "muted_fg")

    def _on_cycle_theme(self) -> None:
        modes = list(THEME_MODES)
        cur = getattr(modules.globals, "ui_theme", "system")
        modules.globals.ui_theme = modes[(modes.index(cur) + 1) % len(modes)] if cur in modes else "system"
        save_switch_states()
        apply_theme(_APP, modules.globals.ui_theme)
        self._refresh_theme_button()
        self._show_page(self._stack.currentIndex())

    # ── helpers ──────────────────────────────────────────────────────────

    def _make_switch(self, field: str, label: str, tip: str, description: str = "") -> SwitchRow:
        sw = SwitchRow(_(label), getattr(modules.globals, field), _(tip),
                       _(description) if description else "")
        sw.toggled.connect(
            lambda v, f=field: (
                setattr(modules.globals, f, v),
                save_switch_states(),
            )
        )
        return sw

    # ── shared face card ─────────────────────────────────────────────────

    def _build_face_card(self) -> QFrame:
        card, layout = _card(_("Your face"), _("A clear, front-facing photo works best."))
        card.setFixedWidth(276)
        self.source_label = _make_image_drop(_("No face\nselected"), (THUMB_SIZE, THUMB_SIZE))
        layout.addWidget(self.source_label, 0, Qt.AlignmentFlag.AlignHCenter)
        self.btn_select_source = _button(_("Choose photo…"), "", "upload")
        self.btn_select_source.setToolTip(_("Choose the source face image to swap onto the target"))
        self.btn_select_source.clicked.connect(self._on_select_source)
        layout.addWidget(self.btn_select_source)
        self.btn_random_face = _button(_("Random AI face"), "ghost", "sparkles", "muted_fg")
        self.btn_random_face.setToolTip(_("Get a random face from thispersondoesnotexist.com"))
        self.btn_random_face.clicked.connect(self._on_random_face)
        layout.addWidget(self.btn_random_face)
        layout.addStretch(1)
        return card

    def _with_face_slot(self, index: int, right: QWidget) -> QHBoxLayout:
        row = QHBoxLayout()
        row.setSpacing(16)
        slot = QVBoxLayout()
        slot.setContentsMargins(0, 0, 0, 0)
        row.addLayout(slot)
        row.addWidget(right, 1)
        self._face_slots[index] = slot
        return row

    # ── live page ────────────────────────────────────────────────────────

    def _build_live_page(self) -> QWidget:
        page, body = self._page(_("Real-time"), _("Live webcam"),
                                _("Swap your face on your webcam in real time and use it in video calls."))

        card, layout = _card(_("Webcam"), _("Choose a camera, then go live. The preview opens in its own window."))
        self._camera_indices, self._camera_names = get_available_cameras()
        self.cb_camera = QComboBox()
        if not self._camera_names or self._camera_names[0] == "No cameras found":
            self.cb_camera.addItem("No cameras found")
            self.cb_camera.setEnabled(False)
            cam_ok = False
        else:
            self.cb_camera.addItems(self._camera_names)
            cam_ok = True
        self.cb_camera.setToolTip(_("Select which camera to use for live mode"))
        layout.addLayout(_field(_("Camera"), self.cb_camera))
        layout.addWidget(_rule())

        self.sw_virtual_cam = self._make_switch(
            "virtual_camera", "Use in video calls",
            "Send the live output to 'OBS Virtual Camera'. Needs OBS Studio installed; "
            "keep OBS's own 'Start Virtual Camera' stopped.",
            "Shows up as “OBS Virtual Camera” in Teams, Zoom or Meet.")
        layout.addWidget(self.sw_virtual_cam)
        self.sw_live_mirror = self._make_switch(
            "live_mirror", "Mirror", "Flip the live image horizontally", "Flip the image like a mirror.")
        layout.addWidget(self.sw_live_mirror)
        self.sw_color_fix = self._make_switch(
            "color_correction", "Fix blueish camera", "Fix blue/green color cast from some webcams",
            "Corrects a blue or green colour cast.")
        layout.addWidget(self.sw_color_fix)
        self.sw_show_fps = self._make_switch(
            "show_fps", "Show FPS", "Display frames-per-second counter on the live preview",
            "Overlay the frame rate on the preview.")
        layout.addWidget(self.sw_show_fps)
        layout.addSpacing(4)

        self.btn_live = _button(_("Go Live"), "primary", "play", "primary_fg", "lg")
        self.btn_live.setEnabled(cam_ok)
        self.btn_live.setToolTip(_("Start real-time face swap using webcam"))
        self.btn_live.clicked.connect(self._on_live)
        layout.addWidget(self.btn_live)
        body.addLayout(self._with_face_slot(self.PAGE_LIVE, card))

        adv, adv_layout = _card(_("Camera settings"), _("Applied the next time you go live."))
        grid = QGridLayout()
        grid.setHorizontalSpacing(16)
        grid.setVerticalSpacing(8)
        self.cb_resolution = QComboBox()
        # 640x480 is native on virtually every webcam and the safest 30fps
        # mode on USB 2.0. Higher tiers are 16:9 and useful when the camera
        # supports them natively (DSLR + capture card, USB 3.0 webcams).
        self._resolution_options = [
            ("640 x 480", (640, 480)),
            ("960 x 540 (qHD)", (960, 540)),
            ("1280 x 720 (HD)", (1280, 720)),
            ("1920 x 1080 (FHD)", (1920, 1080)),
        ]
        for label, _wh in self._resolution_options:
            self.cb_resolution.addItem(label)
        cur = tuple(modules.globals.capture_resolution)
        idx = next((i for i, (_l, wh) in enumerate(self._resolution_options) if wh == cur), 0)
        self.cb_resolution.setCurrentIndex(idx)
        self.cb_resolution.currentIndexChanged.connect(self._on_resolution_change)
        self.cb_resolution.setToolTip(_(
            "Requested webcam resolution. 640x480 is the safest 30fps choice; "
            "HD/FHD can drop to ~10fps on USB 2.0 webcams."
        ))
        grid.addLayout(_field(_("Resolution"), self.cb_resolution), 0, 0)

        self.cb_det_size = QComboBox()
        self._det_size_options = [160, 320, 640, 960, 1280]
        det_labels = {160: _("160 · fastest"), 320: _("320 · fast"), 640: _("640 · balanced"),
                      960: _("960 · HD, finds small faces"), 1280: _("1280 · Full HD, slowest")}
        for v in self._det_size_options:
            self.cb_det_size.addItem(det_labels[v])
        cur_det = int(getattr(modules.globals, 'det_size', modules.globals.DEFAULT_DET_SIZE))
        # Normalize to a valid option first so .index() can never raise.
        if cur_det not in self._det_size_options:
            cur_det = (modules.globals.DEFAULT_DET_SIZE
                       if modules.globals.DEFAULT_DET_SIZE in self._det_size_options
                       else self._det_size_options[-1])
        self.cb_det_size.setCurrentIndex(self._det_size_options.index(cur_det))
        self.cb_det_size.currentIndexChanged.connect(self._on_det_size_change)
        self.cb_det_size.setToolTip(_(
            "How hard the app looks for faces. Higher finds smaller or more distant faces "
            "but costs more time per frame (960 ~1.5x, 1280 ~2.5x). It does not change how "
            "sharp the swapped face is: use Face detail for that."
        ))
        grid.addLayout(_field(_("Face detection"), self.cb_det_size), 0, 1)
        adv_layout.addLayout(grid)
        body.addWidget(adv)
        body.addStretch(1)
        return page

    # ── photo / video page ───────────────────────────────────────────────

    def _build_file_page(self) -> QWidget:
        page, body = self._page(_("Files"), _("Photo & Video"),
                                _("Put your face into a photo or video and save the result as a new file."))

        card, layout = _card(_("Target"), _("The photo or video whose face will be replaced."))
        inner = QHBoxLayout()
        inner.setSpacing(16)
        self.target_label = _make_image_drop(_("No target\nselected"), (THUMB_SIZE, THUMB_SIZE))
        inner.addWidget(self.target_label, 0, Qt.AlignmentFlag.AlignTop)
        buttons = QVBoxLayout()
        buttons.setSpacing(8)
        self.btn_select_target = _button(_("Choose photo or video…"), "", "upload")
        self.btn_select_target.setToolTip(_("Choose the target image or video to apply face swap to"))
        self.btn_select_target.clicked.connect(self._on_select_target)
        buttons.addWidget(self.btn_select_target)
        self.btn_swap = _button(_("Swap face and target"), "ghost", "arrow-left-right", "muted_fg")
        self.btn_swap.setToolTip(_("Swap source and target images"))
        self.btn_swap.clicked.connect(self._on_swap_paths)
        buttons.addWidget(self.btn_swap)
        buttons.addStretch(1)
        inner.addLayout(buttons, 1)
        layout.addLayout(inner)
        layout.addStretch(1)
        body.addLayout(self._with_face_slot(self.PAGE_FILE, card))

        out, out_layout = _card(_("Output"), _("Video options are ignored for photos."))
        self.sw_keep_fps = self._make_switch(
            "keep_fps", "Keep original frame rate", "Output video keeps the original frame rate")
        self.sw_keep_audio = self._make_switch(
            "keep_audio", "Keep audio", "Copy audio track from the source video to output")
        self.sw_keep_frames = self._make_switch(
            "keep_frames", "Keep temporary frames", "Keep extracted frames on disk after processing")
        grid = QGridLayout()
        grid.setHorizontalSpacing(32)
        grid.setVerticalSpacing(4)
        grid.addWidget(self.sw_keep_fps, 0, 0)
        grid.addWidget(self.sw_keep_audio, 0, 1)
        grid.addWidget(self.sw_keep_frames, 1, 0)
        out_layout.addLayout(grid)
        out_layout.addWidget(_rule())
        actions = QHBoxLayout()
        actions.setSpacing(8)
        actions.addStretch(1)
        self.btn_preview = _button(_("Preview"), "", "eye")
        self.btn_preview.setToolTip(_("Show/hide a preview of the processed output"))
        self.btn_preview.clicked.connect(self._on_toggle_preview)
        self.btn_start = _button(_("Convert && save…"), "primary", "save", "primary_fg")
        self.btn_start.setToolTip(_("Process the target with your face and save the result"))
        self.btn_start.clicked.connect(self._on_start)
        actions.addWidget(self.btn_preview)
        actions.addWidget(self.btn_start)
        out_layout.addLayout(actions)
        body.addWidget(out)
        body.addStretch(1)
        return page

    # ── quality page ─────────────────────────────────────────────────────

    def _build_quality_page(self) -> QWidget:
        page, body = self._page(_("Tuning"), _("Face quality"),
                                _("Fine-tune how the swapped face looks. Changes apply instantly, even while live."))

        enh, enh_layout = _card(_("Detail"),
                                _("Higher detail and enhancers give sharper faces but lower live FPS on smaller GPUs."))
        self.cb_enhancer = QComboBox()
        self.cb_enhancer.addItems(["None", "GFPGAN", "GPEN-512", "GPEN-256"])
        initial = "None"
        if modules.globals.fp_ui.get("face_enhancer", False):
            initial = "GFPGAN"
        elif modules.globals.fp_ui.get("face_enhancer_gpen512", False):
            initial = "GPEN-512"
        elif modules.globals.fp_ui.get("face_enhancer_gpen256", False):
            initial = "GPEN-256"
        self.cb_enhancer.setCurrentText(initial)
        self.cb_enhancer.currentTextChanged.connect(self._on_enhancer_change)
        self.cb_enhancer.setToolTip(_("Select a face enhancement model (None = no enhancement)"))
        self.cb_swap_model = QComboBox()
        self._swap_model_keys = list(swap_models.SWAP_MODELS)
        for key in self._swap_model_keys:
            label = swap_models.SWAP_MODELS[key]["label"]
            if not swap_models.is_available(key):
                label += "  ·  " + _("download ~400 MB")
            self.cb_swap_model.addItem(label)
        cur_model = getattr(modules.globals, "swap_model", swap_models.DEFAULT_SWAP_MODEL)
        if cur_model in self._swap_model_keys:
            self.cb_swap_model.setCurrentIndex(self._swap_model_keys.index(cur_model))
        self.cb_swap_model.currentIndexChanged.connect(self._on_swap_model_change)
        self.cb_swap_model.setToolTip(_(
            "HyperSwap swaps at 256px: sharper, keeps hands and objects in front of the face, "
            "and is faster than InSwapper on most GPUs. Models download once when first chosen."))
        enh_layout.addLayout(_field(_("Swap model"), self.cb_swap_model))

        self.cb_detail = QComboBox()
        self._detail_options = [
            (_("Standard · model native (fastest)"), 1),
            (_("High · 2× resolution"), 2),
            (_("Ultra · 4× resolution (photos & video)"), 4),
        ]
        for label, _v in self._detail_options:
            self.cb_detail.addItem(label)
        cur_detail = int(getattr(modules.globals, "face_detail", 1))
        self.cb_detail.setCurrentIndex(
            next((i for i, (_l, v) in enumerate(self._detail_options) if v == cur_detail), 0))
        self.cb_detail.currentIndexChanged.connect(self._on_detail_change)
        self.cb_detail.setToolTip(_(
            "Swaps the face at 2x or 4x the model's resolution for sharper eyes, teeth and skin. "
            "High costs ~4x and Ultra ~16x the time per face, so keep Standard for smooth live video."))
        row = QHBoxLayout()
        row.setSpacing(16)
        row.addLayout(_field(_("Face detail (photos & video)"), self.cb_detail), 1)
        row.addLayout(_field(_("Enhancer model"), self.cb_enhancer), 1)
        enh_layout.addLayout(row)
        enh_layout.addWidget(_hint(_("Face detail applies to photos and videos; live webcam always uses Standard so lips and head movement stay smooth.")))
        body.addWidget(enh)

        blend, blend_layout = _card(_("Blending"), _("Control how strongly the new face is applied."))
        grid = QGridLayout()
        grid.setHorizontalSpacing(16)
        grid.setVerticalSpacing(14)

        def slider(row, name, tip, min_v, max_v, default, denom, on_change, fmt):
            lab = QLabel(_(name))
            lab.setMinimumWidth(110)
            grid.addWidget(lab, row, 0)
            s = QSlider(Qt.Orientation.Horizontal)
            s.setRange(int(min_v * denom), int(max_v * denom))
            s.setValue(int(default * denom))
            s.setToolTip(_(tip))
            value_label = QLabel(fmt(default))
            value_label.setObjectName("sliderValue")
            value_label.setMinimumWidth(40)
            value_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)

            def changed(iv):
                v = iv / denom
                value_label.setText(fmt(v))
                on_change(v)

            s.valueChanged.connect(changed)
            grid.addWidget(s, row, 1)
            grid.addWidget(value_label, row, 2)
            return s

        self.s_transparency = slider(
            0, "Swap strength",
            "Blend between original and swapped face (0% = original, 100% = fully swapped)",
            0.0, 1.0, 1.0, 100, self._on_transparency_change, lambda v: f"{int(v * 100)}%")
        self.s_mouth = slider(
            1, "Mouth mask",
            "0 = use swapped mouth, 100 = keep your real mouth down to the chin "
            "(more natural lip movement)",
            0.0, 100.0, 0.0, 1, self._on_mouth_mask_change, lambda v: f"{int(v)}")
        self.s_mouth.sliderPressed.connect(self._on_mouth_mask_pressed)
        self.s_mouth.sliderReleased.connect(self._on_mouth_mask_released)
        self.s_sharpness = slider(
            2, "Sharpness", "Sharpen the enhanced face output",
            0.0, 5.0, 0.0, 10, self._on_sharpness_change, lambda v: f"{v:.1f}")
        self.s_coverage = slider(
            3, "Face coverage",
            "How much of the head the new face covers. Raise it so the jaw, chin and a beard "
            "are swapped fully instead of fading out at the edge.",
            0.0, 100.0, float(getattr(modules.globals, "mask_coverage", 0.65)) * 100, 1,
            self._on_coverage_change, lambda v: f"{int(v)}")
        self.s_feather = slider(
            4, "Edge softness",
            "How gradually the new face blends into yours. Lower gives a crisper jawline, "
            "higher hides seams in difficult lighting.",
            0.0, 100.0, float(getattr(modules.globals, "mask_feather", 0.45)) * 100, 1,
            self._on_feather_change, lambda v: f"{int(v)}")
        self.s_coverage.sliderReleased.connect(save_switch_states)
        self.s_feather.sliderReleased.connect(save_switch_states)
        grid.setColumnStretch(1, 1)
        blend_layout.addLayout(grid)
        body.addWidget(blend)

        expr, expr_layout = _card(
            _("Expression"),
            _("Keep your real mouth and eyes so talking, smiling and blinking look natural. "
              "Higher shows more of you, lower more of the new face."))
        expr_grid = QGridLayout()
        expr_grid.setHorizontalSpacing(16)
        expr_grid.setVerticalSpacing(14)

        def expr_slider(row, name, tip, field):
            lab = QLabel(_(name))
            lab.setMinimumWidth(110)
            expr_grid.addWidget(lab, row, 0)
            s_ = QSlider(Qt.Orientation.Horizontal)
            s_.setRange(0, 100)
            s_.setValue(int(round(float(getattr(modules.globals, field, 0.0)) * 100)))
            s_.setToolTip(_(tip))
            value = QLabel(str(s_.value()))
            value.setObjectName("sliderValue")
            value.setMinimumWidth(40)
            value.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)

            def changed(iv, f=field, lbl=value):
                lbl.setText(str(iv))
                setattr(modules.globals, f, iv / 100.0)
            s_.valueChanged.connect(changed)
            s_.sliderReleased.connect(save_switch_states)
            expr_grid.addWidget(s_, row, 1)
            expr_grid.addWidget(value, row, 2)
            return s_

        self.s_restore_mouth = expr_slider(
            0, "Real mouth", "Blend your real lips, teeth and tongue back in so speech is in sync",
            "restore_mouth")
        self.s_restore_eyes = expr_slider(
            1, "Real eyes", "Blend your real eyes back in for natural blinks and gaze",
            "restore_eyes")
        expr_grid.setColumnStretch(1, 1)
        expr_layout.addLayout(expr_grid)
        body.addWidget(expr)

        edit, edit_layout = _card(_("Face editing"),
                                  _("Adjust the swapped face itself. Cheap enough to use live."))
        self.sw_color_match = self._make_switch(
            "color_match", "Match skin tone",
            "Match the new face's skin tone and lighting to the scene",
            "Blends the new face's colour and lighting into the scene. Recommended.")
        edit_layout.addWidget(self.sw_color_match)
        edit_grid = QGridLayout()
        edit_grid.setHorizontalSpacing(16)
        edit_grid.setVerticalSpacing(14)

        def edit_slider(row, name, tip, field, min_v, max_v, scale):
            lab = QLabel(_(name))
            lab.setMinimumWidth(110)
            edit_grid.addWidget(lab, row, 0)
            s_ = QSlider(Qt.Orientation.Horizontal)
            s_.setRange(min_v, max_v)
            s_.setValue(int(round(float(getattr(modules.globals, field, 0.0)) * scale)))
            s_.setToolTip(_(tip))
            if min_v < 0:
                s_.setProperty("signed", True)
            value = QLabel(_signed(s_.value()) if min_v < 0 else f"{s_.value()}")
            value.setObjectName("sliderValue")
            value.setMinimumWidth(40)
            value.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)

            def changed(iv, f=field, lbl=value, signed=min_v < 0):
                lbl.setText(_signed(iv) if signed else f"{iv}")
                setattr(modules.globals, f, iv / scale)
                if f == "frame_smoothing":
                    modules.globals.enable_interpolation = iv > 0
                    modules.globals.interpolation_weight = 1.0 - iv / scale
            s_.valueChanged.connect(changed)
            s_.sliderReleased.connect(save_switch_states)
            edit_grid.addWidget(s_, row, 1)
            edit_grid.addWidget(value, row, 2)
            return s_

        self.s_skin = edit_slider(0, "Skin smoothing", "Smooth skin while keeping eyes and lips sharp",
                                  "skin_smoothing", 0, 100, 100)
        self.s_brightness = edit_slider(1, "Brightness", "Lighten or darken the swapped face",
                                        "face_brightness", -50, 50, 50)
        self.s_warmth = edit_slider(2, "Warmth", "Make the swapped face warmer (+) or cooler (-)",
                                    "face_warmth", -50, 50, 50)
        self.s_frame_smooth = edit_slider(3, "Frame smoothing", "Live only: blend frames to reduce flicker. "
                                          "Higher values look steadier but trail on fast movement.",
                                          "frame_smoothing", 0, 80, 100)
        edit_grid.setColumnStretch(1, 1)
        edit_layout.addLayout(edit_grid)
        body.addWidget(edit)

        faces, faces_layout = _card(_("Faces"), _("Choose which faces get swapped."))
        self.sw_many_faces = self._make_switch(
            "many_faces", "Swap all faces", "Swap every detected face, not just the primary one",
            "Replace every face in view, not just the main one.")
        self.sw_poisson = self._make_switch(
            "poisson_blend", "Smooth edges", "Blend face edges smoothly using Poisson blending",
            "Seamless blending around the face edge, for photos and videos (skipped live to keep it smooth).")
        # Map faces is special — closes mapper when toggled off.
        self.sw_map_faces = SwitchRow(
            _("Map faces"), modules.globals.map_faces,
            _("Manually assign which source face maps to which target face"),
            _("Pick a different source face for each person."))
        self.sw_map_faces.toggled.connect(self._on_map_faces_toggled)
        faces_layout.addWidget(self.sw_many_faces)
        faces_layout.addWidget(self.sw_poisson)
        faces_layout.addWidget(self.sw_map_faces)
        body.addWidget(faces)
        body.addStretch(1)
        return page

    def _on_resolution_change(self, idx: int) -> None:
        if 0 <= idx < len(self._resolution_options):
            _label, wh = self._resolution_options[idx]
            modules.globals.capture_resolution = wh
            save_switch_states()
            # Pre-translate the static template; append the dynamic size after
            # so the message still participates in localization (update_status
            # only translates whole-string keys).
            update_status(
                _("Capture resolution set (applies on next Live start):")
                + f" {wh[0]}x{wh[1]}"
            )

    def _on_det_size_change(self, idx: int) -> None:
        if 0 <= idx < len(self._det_size_options):
            v = self._det_size_options[idx]
            modules.globals.det_size = v
            reset_face_analyser()
            save_switch_states()
            update_status(
                _("Face detection size set (analyser re-inits on next call):")
                + f" {v}x{v}"
            )

    # ── slot handlers ────────────────────────────────────────────────────

    def set_status(self, text: str) -> None:
        self._status_label.setText(text)

    def _on_select_source(self) -> None:
        global _RECENT_SOURCE_DIR
        if _PREVIEW is not None:
            _PREVIEW.hide()
        path, _filter = QFileDialog.getOpenFileName(
            self, _("select an source image"),
            _RECENT_SOURCE_DIR or "",
            _IMAGE_FILE_FILTER,
        )
        if path and is_image(path):
            modules.globals.source_path = path
            _RECENT_SOURCE_DIR = os.path.dirname(path)
            self.source_label.setPixmap(render_image_preview(path, (THUMB_SIZE, THUMB_SIZE)))
            self.source_label.setText("")
        elif not path:
            return
        else:
            modules.globals.source_path = None
            self.source_label.clear()
            self.source_label.setText(_("No face\nselected"))

    def _on_select_target(self) -> None:
        global _RECENT_TARGET_DIR
        if _PREVIEW is not None:
            _PREVIEW.hide()
        path, _filter = QFileDialog.getOpenFileName(
            self, _("select an target image or video"),
            _RECENT_TARGET_DIR or "",
            _MEDIA_FILE_FILTER,
        )
        if not path:
            return
        if is_image(path):
            modules.globals.target_path = path
            _RECENT_TARGET_DIR = os.path.dirname(path)
            self.target_label.setPixmap(render_image_preview(path, (THUMB_SIZE, THUMB_SIZE)))
            self.target_label.setText("")
        elif is_video(path):
            modules.globals.target_path = path
            _RECENT_TARGET_DIR = os.path.dirname(path)
            pm = render_video_preview(path, (THUMB_SIZE, THUMB_SIZE))
            if pm:
                self.target_label.setPixmap(pm)
                self.target_label.setText("")
        else:
            modules.globals.target_path = None
            self.target_label.clear()
            self.target_label.setText(_("No target\nselected"))

    def _on_random_face(self) -> None:
        if _PREVIEW is not None:
            _PREVIEW.hide()
        try:
            response = requests.get(
                "https://thispersondoesnotexist.com/random-person.jpeg",
                headers={"User-Agent": "Mozilla/5.0"},
                timeout=10,
            )
            response.raise_for_status()
            content_type = response.headers.get("content-type", "")
            if not content_type.startswith("image/"):
                raise ValueError(f"expected an image, got {content_type!r}")
            temp_path = os.path.join(tempfile.gettempdir(), "deep_live_cam_random_face.jpg")
            staging_path = f"{temp_path}.part"
            # Download into a staging file and validate there. Writing straight
            # to temp_path would destroy the image currently in use whenever a
            # later fetch comes back bad, and content-type alone does not prove
            # the bytes decode.
            try:
                with open(staging_path, "wb") as f:
                    f.write(response.content)
                pixmap = render_image_preview(staging_path, (THUMB_SIZE, THUMB_SIZE))
                if imread_unicode(staging_path) is None:
                    raise ValueError("downloaded image could not be decoded")
                os.replace(staging_path, temp_path)
            except Exception:
                try:
                    os.remove(staging_path)
                except OSError:
                    pass
                raise
            modules.globals.source_path = temp_path
            self.source_label.setPixmap(pixmap)
            self.source_label.setText("")
        except Exception as exc:
            print(f"Failed to fetch random face: {exc}")

    def _on_swap_paths(self) -> None:
        global _RECENT_SOURCE_DIR, _RECENT_TARGET_DIR
        sp = modules.globals.source_path
        tp = modules.globals.target_path
        if not (sp and tp and is_image(sp) and is_image(tp)):
            return
        modules.globals.source_path, modules.globals.target_path = tp, sp
        _RECENT_SOURCE_DIR = os.path.dirname(tp)
        _RECENT_TARGET_DIR = os.path.dirname(sp)
        if _PREVIEW is not None:
            _PREVIEW.hide()
        self.source_label.setPixmap(render_image_preview(tp, (THUMB_SIZE, THUMB_SIZE)))
        self.target_label.setPixmap(render_image_preview(sp, (THUMB_SIZE, THUMB_SIZE)))
        self.source_label.setText("")
        self.target_label.setText("")

    def _on_map_faces_toggled(self, value: bool) -> None:
        modules.globals.map_faces = value
        save_switch_states()
        if not value:
            close_mapper_window()

    def _on_enhancer_change(self, choice: str) -> None:
        key_map = {
            "None": None,
            "GFPGAN": "face_enhancer",
            "GPEN-512": "face_enhancer_gpen512",
            "GPEN-256": "face_enhancer_gpen256",
        }
        for key in ("face_enhancer", "face_enhancer_gpen256", "face_enhancer_gpen512"):
            _update_tumbler(key, False)
        selected = key_map.get(choice)
        if selected:
            _update_tumbler(selected, True)
        save_switch_states()

    def _on_transparency_change(self, value: float) -> None:
        modules.globals.opacity = value
        pct = int(value * 100)
        if pct == 0:
            modules.globals.fp_ui["face_enhancer"] = False
            update_status("Transparency set to 0% - Face swapping disabled.")
        elif pct == 100:
            modules.globals.face_swapper_enabled = True
            update_status("Transparency set to 100%.")
        else:
            modules.globals.face_swapper_enabled = True
            update_status(f"Transparency set to {pct}%")

    def _on_swap_model_change(self, idx: int) -> None:
        if not (0 <= idx < len(self._swap_model_keys)):
            return
        key = self._swap_model_keys[idx]
        info = swap_models.SWAP_MODELS[key]

        def activate() -> None:
            modules.globals.swap_model = key
            save_switch_states()
            from modules.processors.frame.face_swapper import reset_face_swapper
            reset_face_swapper()
            update_status(_("Swap model:") + f" {info['label']}")

        if swap_models.is_available(key):
            activate()
            return

        def worker() -> None:
            if swap_models.download(key, update_status):
                activate()
                # Widgets belong to the UI thread; post the label update there.
                QTimer.singleShot(0, self.cb_swap_model,
                                  lambda: self.cb_swap_model.setItemText(idx, info["label"]))
        update_status(_("Downloading") + f" {info['label']}…")
        threading.Thread(target=worker, daemon=True).start()

    def _on_detail_change(self, idx: int) -> None:
        if 0 <= idx < len(self._detail_options):
            label, value = self._detail_options[idx]
            modules.globals.face_detail = value
            save_switch_states()
            update_status(_("Face detail:") + f" {label}")

    def _on_coverage_change(self, value: float) -> None:
        modules.globals.mask_coverage = value / 100.0

    def _on_feather_change(self, value: float) -> None:
        modules.globals.mask_feather = value / 100.0

    def _on_sharpness_change(self, value: float) -> None:
        modules.globals.sharpness = value
        update_status(f"Sharpness set to {value:.1f}")

    def _on_mouth_mask_change(self, value: float) -> None:
        modules.globals.mouth_mask_size = value
        modules.globals.mouth_mask = value > 0
        if value <= 0:
            modules.globals.show_mouth_mask_box = False

    def _on_mouth_mask_pressed(self) -> None:
        if modules.globals.mouth_mask_size > 0:
            modules.globals.show_mouth_mask_box = True

    def _on_mouth_mask_released(self) -> None:
        modules.globals.show_mouth_mask_box = False

    def _on_start(self) -> None:
        if _MAPPER is not None and _MAPPER.isVisible():
            update_status("Please complete pop-up or close it.")
            return
        if modules.globals.map_faces:
            modules.globals.source_target_map = []
            if is_image(modules.globals.target_path):
                update_status("Getting unique faces")
                get_unique_faces_from_target_image()
            elif is_video(modules.globals.target_path):
                update_status("Getting unique faces")
                get_unique_faces_from_target_video()
            if modules.globals.source_target_map:
                _open_mapper_dialog(self._start_cb, modules.globals.source_target_map)
            else:
                update_status("No faces found in target")
        else:
            self._select_output_and_start()

    def _select_output_and_start(self) -> None:
        global _RECENT_OUTPUT_DIR
        if is_image(modules.globals.target_path):
            path, _f = QFileDialog.getSaveFileName(
                self, _("save image output file"),
                os.path.join(_RECENT_OUTPUT_DIR or "", "output.png"),
                _IMAGE_FILE_FILTER,
            )
        elif is_video(modules.globals.target_path):
            path, _f = QFileDialog.getSaveFileName(
                self, _("save video output file"),
                os.path.join(_RECENT_OUTPUT_DIR or "", "output.mp4"),
                _VIDEO_FILE_FILTER,
            )
        else:
            update_status(
                "Start converts a photo/video file: click 'Select a target' first. "
                "For webcam use 'Live'."
            )
            return
        if path:
            modules.globals.output_path = path
            _RECENT_OUTPUT_DIR = os.path.dirname(path)
            self._start_cb()

    def _on_toggle_preview(self) -> None:
        if _PREVIEW is None:
            return
        if _PREVIEW.isVisible():
            _PREVIEW.hide()
        elif modules.globals.source_path and modules.globals.target_path:
            _PREVIEW.init_for_target()
            _PREVIEW.refresh_frame(0)
            _PREVIEW.show()

    def _on_live(self) -> None:
        idx = self.cb_camera.currentIndex()
        if idx < 0 or idx >= len(self._camera_indices):
            update_status("No camera available")
            return
        camera_index = self._camera_indices[idx]
        if _LIVE_MAPPER is not None and _LIVE_MAPPER.isVisible():
            update_status("Source x Target Mapper is already open.")
            _LIVE_MAPPER.raise_()
            return
        if not modules.globals.map_faces:
            if modules.globals.source_path is None:
                update_status("Please select a source image first")
                return
            from modules.face_analyser import get_face_analyser
            from modules.processors.frame.face_swapper import get_face_swapper
            get_face_analyser()
            get_face_swapper()
            _open_webcam_preview(camera_index)
        else:
            modules.globals.source_target_map = []
            _open_live_mapper_dialog(camera_index, modules.globals.source_target_map)

    def closeEvent(self, event):
        # Treat OS-level close as Destroy click
        self._destroy_cb()
        event.accept()


def _update_tumbler(var: str, value: bool) -> None:
    modules.globals.fp_ui[var] = value
    save_switch_states()
    # If we're currently in a live preview, refresh frame processors so
    # toggling enhancers takes effect immediately.
    if _WEBCAM_PREVIEW is not None and _WEBCAM_PREVIEW.isVisible():
        get_frame_processors_modules(modules.globals.frame_processors)


# ─── preview window (still-image / video scrub) ──────────────────────────


class PreviewWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle(f"{modules.metadata.name} · {_('Preview')}")
        self.resize(PREVIEW_DEFAULT_WIDTH, PREVIEW_DEFAULT_HEIGHT)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._image_label = QLabel()
        self._image_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._image_label.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        layout.addWidget(self._image_label, 1)

        self._slider = QSlider(Qt.Orientation.Horizontal)
        self._slider.setRange(0, 0)
        self._slider.valueChanged.connect(self.refresh_frame)
        layout.addWidget(self._slider)

    def init_for_target(self) -> None:
        if is_image(modules.globals.target_path):
            self._slider.hide()
        elif is_video(modules.globals.target_path):
            total = get_video_frame_total(modules.globals.target_path)
            self._slider.setRange(0, max(0, total - 1))
            self._slider.setValue(0)
            self._slider.show()

    def refresh_frame(self, frame_number: int = 0) -> None:
        if not (modules.globals.source_path and modules.globals.target_path):
            return
        update_status("Processing...")
        if is_image(modules.globals.target_path):
            temp_frame = imread_unicode(modules.globals.target_path)
        else:
            temp_frame = get_video_frame(modules.globals.target_path, frame_number)
        if temp_frame is None:
            update_status(
                f"Could not read target: {modules.globals.target_path}"
            )
            return
        if modules.globals.nsfw_filter and check_and_ignore_nsfw(temp_frame):
            return
        source_frame = imread_unicode(modules.globals.source_path)
        if source_frame is None:
            update_status(
                f"Could not read source image: {modules.globals.source_path}"
            )
            return
        from modules.processors.frame.core import get_frame_processors_modules as _gfpm
        for fp in _gfpm(modules.globals.frame_processors):
            temp_frame = fp.process_frame(get_source_face(source_frame), temp_frame)
        # Fit to current widget size while preserving aspect ratio.
        h, w = temp_frame.shape[:2]
        bound_w = min(PREVIEW_MAX_WIDTH, max(self.width(), PREVIEW_DEFAULT_WIDTH))
        bound_h = min(PREVIEW_MAX_HEIGHT, max(self.height(), PREVIEW_DEFAULT_HEIGHT))
        ratio = min(bound_w / w, bound_h / h)
        new_size = (max(1, int(w * ratio)), max(1, int(h * ratio)))
        temp_frame = cv2.resize(temp_frame, new_size, interpolation=cv2.INTER_LANCZOS4)
        self._image_label.setPixmap(_bgr_to_qpixmap(temp_frame))
        update_status("Processing succeed!")


# ─── webcam preview window ───────────────────────────────────────────────


class _CaptureWorker(QThread):
    """Reads frames from the camera into a bounded queue. Drops on overflow."""

    def __init__(self, cap, capture_queue: queue.Queue, stop_event: threading.Event):
        super().__init__()
        self._cap = cap
        self._queue = capture_queue
        self._stop = stop_event

    def run(self) -> None:
        while not self._stop.is_set():
            ret, frame = self._cap.read()
            if not ret:
                self._stop.set()
                break
            try:
                self._queue.put_nowait(frame)
            except queue.Full:
                try:
                    self._queue.get_nowait()
                except queue.Empty:
                    pass
                try:
                    self._queue.put_nowait(frame)
                except queue.Full:
                    pass


class _ProcessingWorker(QThread):
    """Pulls raw frames, runs detect/swap/enhance, pushes processed frames."""

    def __init__(self, capture_queue, processed_queue, stop_event, camera_fps: float):
        super().__init__()
        self._cq = capture_queue
        self._pq = processed_queue
        self._stop = stop_event
        self._fps = camera_fps

    def run(self) -> None:
        set_live_thread(True)
        vcam = VirtualCamOutput()
        try:
            self._run_loop(vcam)
        finally:
            vcam.close()

    def _run_loop(self, vcam: VirtualCamOutput) -> None:
        frame_processors = get_frame_processors_modules(modules.globals.frame_processors)
        source_image = None
        last_source_path = None
        reported_source_error = None
        prev_time = time.time()
        fps_update_interval = 0.5
        frame_count = 0
        fps = 0.0
        det_count = 0
        cached_target_face = None
        cached_many_faces = None
        det_interval = max(1, round(self._fps * 0.08))

        while not self._stop.is_set():
            try:
                frame = self._cq.get(timeout=0.05)
            except queue.Empty:
                continue

            temp_frame = frame
            if modules.globals.live_mirror:
                temp_frame = gpu_flip(temp_frame, 1)

            if not modules.globals.map_faces:
                if (
                    modules.globals.source_path
                    and modules.globals.source_path != last_source_path
                ):
                    source_frame = imread_unicode(modules.globals.source_path)
                    if source_frame is None:
                        # Clear the cached path along with the image. It keeps
                        # a source that is only transiently unreadable (still
                        # being written, on a volume that just went away) from
                        # being given up on, and it keeps a bad pick from
                        # sticking: with the path cached, A -> unreadable B -> A
                        # never reloaded A, so swapping stayed off. Retrying
                        # every frame is cheap; the message is reported once per
                        # path so it cannot flood the status line.
                        source_image = None
                        last_source_path = None
                        if reported_source_error != modules.globals.source_path:
                            reported_source_error = modules.globals.source_path
                            update_status(
                                f"Could not read source image: {modules.globals.source_path}"
                            )
                    else:
                        last_source_path = modules.globals.source_path
                        reported_source_error = None
                        source_image = get_source_face(source_frame)
                        if source_image is None:
                            update_status(
                                "No face found in the source image - try a clearer, front-facing photo"
                            )

                det_count += 1
                if det_count % det_interval == 0:
                    if modules.globals.many_faces:
                        cached_target_face = None
                        cached_many_faces = detect_many_faces_fast(temp_frame)
                    else:
                        cached_target_face = detect_one_face_fast(temp_frame)
                        cached_many_faces = None

                cached_faces = None
                if cached_many_faces:
                    cached_faces = cached_many_faces
                elif cached_target_face is not None:
                    cached_faces = [cached_target_face]

                # Fast detection skips the 2d106 landmark model, but the mouth
                # mask needs it. Attach landmarks on demand (computed once per
                # detection cycle — the helper no-ops if already present).
                needs_landmarks = (modules.globals.mouth_mask
                                   or getattr(modules.globals, "restore_mouth", 0) > 0
                                   or getattr(modules.globals, "restore_eyes", 0) > 0)
                if needs_landmarks and cached_faces:
                    ensure_landmarks(temp_frame, cached_faces)

                for fp in frame_processors:
                    if fp.NAME == "DLC.FACE-ENHANCER":
                        if modules.globals.fp_ui["face_enhancer"]:
                            temp_frame = fp.process_frame(
                                None, temp_frame, detected_faces=cached_faces
                            )
                    elif fp.NAME == "DLC.FACE-ENHANCER-GPEN256":
                        if modules.globals.fp_ui.get("face_enhancer_gpen256", False):
                            temp_frame = fp.process_frame(
                                None, temp_frame, detected_faces=cached_faces
                            )
                    elif fp.NAME == "DLC.FACE-ENHANCER-GPEN512":
                        if modules.globals.fp_ui.get("face_enhancer_gpen512", False):
                            temp_frame = fp.process_frame(
                                None, temp_frame, detected_faces=cached_faces
                            )
                    elif fp.NAME == "DLC.FACE-SWAPPER":
                        swapped_bboxes = []
                        if modules.globals.many_faces and cached_many_faces:
                            result = temp_frame.copy()
                            for t_face in cached_many_faces:
                                result = fp.swap_face(source_image, t_face, result)
                                if hasattr(t_face, "bbox") and t_face.bbox is not None:
                                    swapped_bboxes.append(t_face.bbox.astype(int))
                            temp_frame = result
                        elif cached_target_face is not None:
                            temp_frame = fp.swap_face(
                                source_image, cached_target_face, temp_frame
                            )
                            if (
                                hasattr(cached_target_face, "bbox")
                                and cached_target_face.bbox is not None
                            ):
                                swapped_bboxes.append(cached_target_face.bbox.astype(int))
                        temp_frame = fp.apply_post_processing(
                            temp_frame, swapped_bboxes, allow_temporal=True
                        )
                    else:
                        temp_frame = fp.process_frame(source_image, temp_frame)
            else:
                modules.globals.target_path = None
                for fp in frame_processors:
                    if fp.NAME == "DLC.FACE-ENHANCER":
                        if modules.globals.fp_ui["face_enhancer"]:
                            temp_frame = fp.process_frame_v2(temp_frame)
                    elif fp.NAME in ("DLC.FACE-ENHANCER-GPEN256", "DLC.FACE-ENHANCER-GPEN512"):
                        fp_key = fp.NAME.split(".")[-1].lower().replace("-", "_")
                        if modules.globals.fp_ui.get(fp_key, False):
                            temp_frame = fp.process_frame_v2(temp_frame)
                    else:
                        temp_frame = fp.process_frame_v2(temp_frame)

            current_time = time.time()
            frame_count += 1
            if current_time - prev_time >= fps_update_interval:
                fps = frame_count / (current_time - prev_time)
                frame_count = 0
                prev_time = current_time

            if modules.globals.show_fps:
                cv2.putText(
                    temp_frame, f"FPS: {fps:.1f}", (10, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2,
                )

            if modules.globals.virtual_camera:
                vcam.send(temp_frame)
            else:
                vcam.close()

            try:
                self._pq.put_nowait(temp_frame)
            except queue.Full:
                try:
                    self._pq.get_nowait()
                except queue.Empty:
                    pass
                try:
                    self._pq.put_nowait(temp_frame)
                except queue.Full:
                    pass


class WebcamPreviewWindow(QWidget):
    def __init__(self, camera_index: int):
        super().__init__()
        self.setWindowTitle(f"{modules.metadata.name} · {_('Live')}")
        self.setObjectName("livePreview")
        self.resize(PREVIEW_DEFAULT_WIDTH, PREVIEW_DEFAULT_HEIGHT + 38)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        self._image_label = QLabel()
        self._image_label.setObjectName("liveCanvas")
        self._image_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._image_label.setSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        layout.addWidget(self._image_label, 1)

        bar = QFrame()
        bar.setObjectName("statusBar")
        bar.setFixedHeight(38)
        row = QHBoxLayout(bar)
        row.setContentsMargins(14, 0, 14, 0)
        row.setSpacing(10)
        live_pill = QLabel(_("LIVE"))
        live_pill.setObjectName("livePill")
        row.addWidget(live_pill)
        self._info_label = QLabel(_("Starting camera…"))
        self._info_label.setObjectName("statusLabel")
        row.addWidget(self._info_label, 1)
        self._vcam_pill = QLabel()
        self._vcam_pill.setObjectName("pill")
        row.addWidget(self._vcam_pill)
        layout.addWidget(bar)
        self._shown_frames = 0
        self._fps_t0 = time.time()

        self._cap = VideoCapturer(camera_index)
        req_w, req_h = modules.globals.capture_resolution
        if not self._cap.start(req_w, req_h, 60):
            update_status("Failed to start camera")
            QTimer.singleShot(0, self.close)
            return

        camera_fps = self._cap.actual_fps
        print(
            f"[webcam] Camera running at {self._cap.actual_width}x"
            f"{self._cap.actual_height}@{camera_fps:.0f}fps"
        )
        if camera_fps < 5:
            update_status(
                f"Camera is very slow ({camera_fps:.0f} fps). It may be in use by "
                "another app (Teams, NVIDIA Broadcast) - close it or pick another camera."
            )

        self._capture_queue: queue.Queue = queue.Queue(maxsize=2)
        self._processed_queue: queue.Queue = queue.Queue(maxsize=2)
        self._stop_event = threading.Event()

        self._capture_worker = _CaptureWorker(
            self._cap, self._capture_queue, self._stop_event
        )
        self._processing_worker = _ProcessingWorker(
            self._capture_queue, self._processed_queue, self._stop_event, camera_fps
        )
        self._capture_worker.start()
        self._processing_worker.start()

        # Poll at ~2x camera fps so we never block but also don't burn CPU.
        poll_ms = max(1, min(16, int(500 / max(camera_fps, 1))))
        self._timer = QTimer(self)
        self._timer.timeout.connect(self._tick)
        self._timer.start(poll_ms)

    def _tick(self) -> None:
        if self._stop_event.is_set():
            self.close()
            return
        try:
            bgr_frame = self._processed_queue.get_nowait()
        except queue.Empty:
            return
        bgr_frame = fit_image_to_size(
            bgr_frame, self._image_label.width(), self._image_label.height()
        )
        self._image_label.setPixmap(_bgr_to_qpixmap(bgr_frame))
        self._shown_frames += 1
        elapsed = time.time() - self._fps_t0
        if elapsed >= 1.0:
            self._info_label.setText(
                f"{self._cap.actual_width}×{self._cap.actual_height} · "
                f"{self._shown_frames / elapsed:.0f} fps"
            )
            self._vcam_pill.setText(
                _("Video calls: on") if modules.globals.virtual_camera else _("Video calls: off")
            )
            self._shown_frames = 0
            self._fps_t0 = time.time()

    def closeEvent(self, event) -> None:
        # __init__ can bail out before these exist (e.g. the camera fails to open),
        # and closeEvent still runs.
        stop_event = getattr(self, "_stop_event", None)
        if stop_event is not None:
            stop_event.set()
        timer = getattr(self, "_timer", None)
        if timer is not None:
            try:
                timer.stop()
            except Exception:
                pass
        # Shutdown has to actually complete. Qt aborts the process when a
        # running QThread is destroyed, and holding a straggler in a module
        # global only moves that abort to interpreter exit. Both loops re-check
        # the stop flag between bounded operations (a camera read, a 50ms queue
        # get, one inference), so waiting terminates; a first-time model load
        # is simply slow, which is what the grace period absorbs quietly.
        for name in ("_capture_worker", "_processing_worker"):
            worker = getattr(self, name, None)
            if worker is None:
                continue
            if not worker.wait(WORKER_SHUTDOWN_GRACE_MS):
                print(
                    f"[webcam] still waiting for {name[1:]} to stop...",
                    flush=True,
                )
                worker.wait()
        # Only now: releasing the capture while the capture thread could still
        # be inside cap.read() is not safe.
        cap = getattr(self, "_cap", None)
        if cap is not None:
            try:
                cap.release()
            except Exception:
                pass
        global _WEBCAM_PREVIEW
        if _WEBCAM_PREVIEW is self:
            _WEBCAM_PREVIEW = None
        event.accept()


def _open_webcam_preview(camera_index: int) -> None:
    global _WEBCAM_PREVIEW
    if _WEBCAM_PREVIEW is not None:
        _WEBCAM_PREVIEW.close()
    _WEBCAM_PREVIEW = WebcamPreviewWindow(camera_index)
    _WEBCAM_PREVIEW.show()


# ─── mapper dialogs (image/video + live) ────────────────────────────────


def _make_thumb(cv2_img: np.ndarray) -> QPixmap:
    rgb = gpu_cvt_color(cv2_img, cv2.COLOR_BGR2RGB)
    image = Image.fromarray(rgb).resize(
        (MAPPER_PREVIEW_SIZE, MAPPER_PREVIEW_SIZE), Image.LANCZOS
    )
    return _pil_to_qpixmap(image)


class MapperDialog(QDialog):
    """Source × Target mapper for image / video processing."""

    def __init__(self, start_cb: Callable, mapping: list):
        super().__init__(_MAIN)
        self._start_cb = start_cb
        self._map = mapping
        self.setWindowTitle(_("Source x Target Mapper"))
        self.resize(POPUP_WIDTH, POPUP_HEIGHT)
        layout = QVBoxLayout(self)

        self._scroll = QScrollArea()
        self._scroll.setWidgetResizable(True)
        layout.addWidget(self._scroll, 1)

        self._status = QLabel("")
        self._status.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self._status)

        btn_submit = QPushButton(_("Submit"))
        btn_submit.clicked.connect(self._on_submit)
        layout.addWidget(btn_submit, alignment=Qt.AlignmentFlag.AlignCenter)

        self._rebuild()

    def set_status(self, text: str) -> None:
        self._status.setText(_(text))

    def _rebuild(self) -> None:
        body = QWidget()
        grid = QGridLayout(body)
        grid.setHorizontalSpacing(10)
        grid.setVerticalSpacing(10)
        for item in self._map:
            row = item["id"]
            btn = QPushButton(_("Select source image"))
            btn.setFixedWidth(200)
            btn.clicked.connect(lambda _c, n=row: self._select_source(n))
            grid.addWidget(btn, row, 0)

            src_label = QLabel(f"S-{row}")
            src_label.setFixedSize(MAPPER_PREVIEW_SIZE, MAPPER_PREVIEW_SIZE)
            src_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            src_label.setStyleSheet(f"border: 1px dashed {theme_tokens()['input']}; border-radius: 8px;")
            grid.addWidget(src_label, row, 1)
            if "source" in item:
                src_label.setPixmap(_make_thumb(item["source"]["cv2"]))
                src_label.setText("")

            x_label = QLabel("×")
            x_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            grid.addWidget(x_label, row, 2)

            tgt_label = QLabel(f"T-{row}")
            tgt_label.setFixedSize(MAPPER_PREVIEW_SIZE, MAPPER_PREVIEW_SIZE)
            tgt_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            tgt_label.setStyleSheet(f"border: 1px solid {theme_tokens()['border']}; border-radius: 8px;")
            grid.addWidget(tgt_label, row, 3)
            if "target" in item:
                tgt_label.setPixmap(_make_thumb(item["target"]["cv2"]))
                tgt_label.setText("")

        grid.setRowStretch(grid.rowCount(), 1)
        self._scroll.setWidget(body)

    def _select_source(self, row: int) -> None:
        path, _f = QFileDialog.getOpenFileName(
            self, _("select an source image"),
            _RECENT_SOURCE_DIR or "",
            _IMAGE_FILE_FILTER,
        )
        if not path:
            return
        cv2_img = imread_unicode(path)
        face = get_one_face(cv2_img)
        if face is None:
            self.set_status("Face could not be detected in last upload!")
            return
        x_min, y_min, x_max, y_max = face["bbox"]
        self._map[row]["source"] = {
            "cv2": cv2_img[int(y_min):int(y_max), int(x_min):int(x_max)],
            "face": face,
        }
        self._rebuild()

    def _on_submit(self) -> None:
        if has_valid_map():
            self.accept()
            _MAIN._select_output_and_start()
        else:
            self.set_status("Atleast 1 source with target is required!")


class LiveMapperDialog(QDialog):
    """Source × Target mapper for live webcam mode."""

    def __init__(self, camera_index: int, mapping: list):
        super().__init__(_MAIN)
        self._camera_index = camera_index
        self._map = mapping
        self.setWindowTitle(_("Source x Target Mapper"))
        self.resize(POPUP_LIVE_WIDTH, POPUP_LIVE_HEIGHT)
        layout = QVBoxLayout(self)

        self._scroll = QScrollArea()
        self._scroll.setWidgetResizable(True)
        layout.addWidget(self._scroll, 1)

        self._status = QLabel("")
        self._status.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self._status)

        btn_row = QHBoxLayout()
        for text, slot in (
            (_("Add"), self._on_add),
            (_("Clear"), self._on_clear),
            (_("Submit"), self._on_submit),
        ):
            b = QPushButton(text)
            b.clicked.connect(slot)
            btn_row.addWidget(b)
        layout.addLayout(btn_row)

        self._rebuild()

    def set_status(self, text: str) -> None:
        self._status.setText(_(text))

    def _rebuild(self) -> None:
        body = QWidget()
        grid = QGridLayout(body)
        grid.setHorizontalSpacing(10)
        grid.setVerticalSpacing(10)
        for item in self._map:
            row = item["id"]
            btn_s = QPushButton(_("Select source image"))
            btn_s.setFixedWidth(200)
            btn_s.clicked.connect(lambda _c, n=row: self._select_face(n, "source"))
            grid.addWidget(btn_s, row, 0)

            src_label = QLabel(f"S-{row}")
            src_label.setFixedSize(MAPPER_PREVIEW_SIZE, MAPPER_PREVIEW_SIZE)
            src_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            src_label.setStyleSheet(f"border: 1px dashed {theme_tokens()['input']}; border-radius: 8px;")
            grid.addWidget(src_label, row, 1)
            if "source" in item:
                src_label.setPixmap(_make_thumb(item["source"]["cv2"]))
                src_label.setText("")

            x_label = QLabel("×")
            x_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            grid.addWidget(x_label, row, 2)

            btn_t = QPushButton(_("Select target image"))
            btn_t.setFixedWidth(200)
            btn_t.clicked.connect(lambda _c, n=row: self._select_face(n, "target"))
            grid.addWidget(btn_t, row, 3)

            tgt_label = QLabel(f"T-{row}")
            tgt_label.setFixedSize(MAPPER_PREVIEW_SIZE, MAPPER_PREVIEW_SIZE)
            tgt_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            tgt_label.setStyleSheet(f"border: 1px dashed {theme_tokens()['input']}; border-radius: 8px;")
            grid.addWidget(tgt_label, row, 4)
            if "target" in item:
                tgt_label.setPixmap(_make_thumb(item["target"]["cv2"]))
                tgt_label.setText("")

        grid.setRowStretch(grid.rowCount(), 1)
        self._scroll.setWidget(body)

    def _select_face(self, row: int, kind: str) -> None:
        path, _f = QFileDialog.getOpenFileName(
            self, _("select an source image"),
            _RECENT_SOURCE_DIR or "",
            _IMAGE_FILE_FILTER,
        )
        if not path:
            return
        cv2_img = imread_unicode(path)
        face = get_one_face(cv2_img)
        if face is None:
            self.set_status("Face could not be detected in last upload!")
            return
        x_min, y_min, x_max, y_max = face["bbox"]
        self._map[row][kind] = {
            "cv2": cv2_img[int(y_min):int(y_max), int(x_min):int(x_max)],
            "face": face,
        }
        self._rebuild()

    def _on_add(self) -> None:
        add_blank_map()
        self._rebuild()
        self.set_status("Please provide mapping!")

    def _on_clear(self) -> None:
        for item in self._map:
            item.pop("source", None)
            item.pop("target", None)
        self._rebuild()
        self.set_status("All mappings cleared!")

    def _on_submit(self) -> None:
        if has_valid_map():
            simplify_maps()
            self.set_status("Mappings successfully submitted!")
            self.accept()
            _open_webcam_preview(self._camera_index)
        else:
            self.set_status("At least 1 source with target is required!")


def _open_mapper_dialog(start_cb: Callable, mapping: list) -> None:
    global _MAPPER
    close_mapper_window()
    _MAPPER = MapperDialog(start_cb, mapping)
    _MAPPER.show()


def _open_live_mapper_dialog(camera_index: int, mapping: list) -> None:
    global _LIVE_MAPPER
    close_mapper_window()
    _LIVE_MAPPER = LiveMapperDialog(camera_index, mapping)
    _LIVE_MAPPER.show()


def close_mapper_window() -> None:
    global _MAPPER, _LIVE_MAPPER
    if _MAPPER is not None:
        _MAPPER.close()
        _MAPPER = None
    if _LIVE_MAPPER is not None:
        _LIVE_MAPPER.close()
        _LIVE_MAPPER = None


# ─── entry point ─────────────────────────────────────────────────────────


def _close_live_windows() -> None:
    """Close every window that owns worker threads, so the threads stop."""
    for win in (_WEBCAM_PREVIEW, _LIVE_MAPPER):
        if win is None:
            continue
        try:
            win.close()
        except Exception:
            pass


class _Window:
    """Thin wrapper exposing .mainloop() for core.py compatibility."""

    def __init__(self, app: QApplication, main_window: MainWindow):
        self._app = app
        self._main = main_window

    def mainloop(self) -> None:
        self._main.show()
        self._app.exec()


def _on_system_theme_changed(*_args) -> None:
    if getattr(modules.globals, "ui_theme", "system") == "system" and _APP is not None:
        apply_theme(_APP, "system")


def init(
    start: Callable[[], None], destroy: Callable[[], None], lang: str
) -> _Window:
    global _APP, _MAIN, _PREVIEW, _LANG, _BRIDGE

    _LANG = LanguageManager(lang)
    if QApplication.instance() is None:
        _APP = QApplication(sys.argv)
    else:
        _APP = QApplication.instance()
    apply_theme(_APP, getattr(modules.globals, "ui_theme", "system"))
    _APP.setApplicationName(modules.metadata.name)
    if os.path.exists(APP_ICON_ICO):
        _APP.setWindowIcon(QIcon(APP_ICON_ICO))
    if sys.platform == "win32":
        # Own taskbar identity, so Windows shows our icon instead of python.exe's.
        try:
            import ctypes
            ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("LiveFaceCam.App")
        except Exception:
            pass
    try:
        _APP.styleHints().colorSchemeChanged.connect(_on_system_theme_changed)
    except Exception:
        pass

    _BRIDGE = _UIBridge()
    def _destroy_with_cleanup(*args, **kwargs):
        # core.destroy() ends in a bare quit(), which raises SystemExit and tears
        # the interpreter down without unwinding Qt. Destroying a running QThread
        # is fatal in Qt, so stop the live-preview workers before that happens.
        _close_live_windows()
        return destroy(*args, **kwargs)

    _MAIN = MainWindow(start, _destroy_with_cleanup)
    _PREVIEW = PreviewWindow()

    # Route status updates onto the UI thread regardless of caller.
    _BRIDGE.statusChanged.connect(_MAIN.set_status)

    return _Window(_APP, _MAIN)
